
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry pantalla;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button bvaciar;

	private global::Gtk.Button c;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button siete;

	private global::Gtk.Button ocho;

	private global::Gtk.Button nueve;

	private global::Gtk.Button division;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button cuatro;

	private global::Gtk.Button cinco;

	private global::Gtk.Button seis;

	private global::Gtk.Button multiplicacion;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button uno;

	private global::Gtk.Button dos;

	private global::Gtk.Button tres;

	private global::Gtk.Button resta;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button button13;

	private global::Gtk.Button cero;

	private global::Gtk.Button button15;

	private global::Gtk.Button suma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora Cigalat");
		this.vbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.pantalla = new global::Gtk.Entry();
		this.pantalla.CanFocus = true;
		this.pantalla.Name = "pantalla";
		this.pantalla.IsEditable = true;
		this.pantalla.InvisibleChar = '•';
		this.vbox1.Add(this.pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.pantalla]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bvaciar = new global::Gtk.Button();
		this.bvaciar.CanFocus = true;
		this.bvaciar.Name = "bvaciar";
		this.bvaciar.UseUnderline = true;
		this.bvaciar.Label = global::Mono.Unix.Catalog.GetString("Vaciar");
		this.hbox1.Add(this.bvaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.bvaciar]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.c = new global::Gtk.Button();
		this.c.CanFocus = true;
		this.c.Name = "c";
		this.c.UseUnderline = true;
		this.c.Label = global::Mono.Unix.Catalog.GetString("c");
		this.hbox1.Add(this.c);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.c]));
		w4.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.siete = new global::Gtk.Button();
		this.siete.CanFocus = true;
		this.siete.Name = "siete";
		this.siete.UseUnderline = true;
		this.siete.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox2.Add(this.siete);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.siete]));
		w6.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.ocho = new global::Gtk.Button();
		this.ocho.CanFocus = true;
		this.ocho.Name = "ocho";
		this.ocho.UseUnderline = true;
		this.ocho.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox2.Add(this.ocho);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ocho]));
		w7.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.nueve = new global::Gtk.Button();
		this.nueve.CanFocus = true;
		this.nueve.Name = "nueve";
		this.nueve.UseUnderline = true;
		this.nueve.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox2.Add(this.nueve);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.nueve]));
		w8.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.division = new global::Gtk.Button();
		this.division.CanFocus = true;
		this.division.Name = "division";
		this.division.UseUnderline = true;
		this.division.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox2.Add(this.division);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.division]));
		w9.Position = 3;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cuatro = new global::Gtk.Button();
		this.cuatro.CanFocus = true;
		this.cuatro.Name = "cuatro";
		this.cuatro.UseUnderline = true;
		this.cuatro.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox3.Add(this.cuatro);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cuatro]));
		w11.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cinco = new global::Gtk.Button();
		this.cinco.CanFocus = true;
		this.cinco.Name = "cinco";
		this.cinco.UseUnderline = true;
		this.cinco.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox3.Add(this.cinco);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cinco]));
		w12.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.seis = new global::Gtk.Button();
		this.seis.CanFocus = true;
		this.seis.Name = "seis";
		this.seis.UseUnderline = true;
		this.seis.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox3.Add(this.seis);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.seis]));
		w13.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.multiplicacion = new global::Gtk.Button();
		this.multiplicacion.CanFocus = true;
		this.multiplicacion.Name = "multiplicacion";
		this.multiplicacion.UseUnderline = true;
		this.multiplicacion.Label = global::Mono.Unix.Catalog.GetString("X");
		this.hbox3.Add(this.multiplicacion);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.multiplicacion]));
		w14.Position = 3;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.uno = new global::Gtk.Button();
		this.uno.CanFocus = true;
		this.uno.Name = "uno";
		this.uno.UseUnderline = true;
		this.uno.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox4.Add(this.uno);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.uno]));
		w16.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.dos = new global::Gtk.Button();
		this.dos.CanFocus = true;
		this.dos.Name = "dos";
		this.dos.UseUnderline = true;
		this.dos.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox4.Add(this.dos);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.dos]));
		w17.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.tres = new global::Gtk.Button();
		this.tres.CanFocus = true;
		this.tres.Name = "tres";
		this.tres.UseUnderline = true;
		this.tres.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox4.Add(this.tres);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.tres]));
		w18.Position = 2;
		// Container child hbox4.Gtk.Box+BoxChild
		this.resta = new global::Gtk.Button();
		this.resta.CanFocus = true;
		this.resta.Name = "resta";
		this.resta.UseUnderline = true;
		this.resta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox4.Add(this.resta);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.resta]));
		w19.Position = 3;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox5.Add(this.button13);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button13]));
		w21.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.cero = new global::Gtk.Button();
		this.cero.CanFocus = true;
		this.cero.Name = "cero";
		this.cero.UseUnderline = true;
		this.cero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox5.Add(this.cero);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.cero]));
		w22.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox5.Add(this.button15);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button15]));
		w23.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.suma = new global::Gtk.Button();
		this.suma.CanFocus = true;
		this.suma.Name = "suma";
		this.suma.UseUnderline = true;
		this.suma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox5.Add(this.suma);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.suma]));
		w24.Position = 3;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w25.Position = 6;
		w25.Expand = false;
		w25.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 160;
		this.DefaultHeight = 235;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.bvaciar.Clicked += new global::System.EventHandler(this.OnBvaciarClicked);
		this.c.Clicked += new global::System.EventHandler(this.OnCClicked);
		this.siete.Clicked += new global::System.EventHandler(this.OnSieteClicked);
		this.ocho.Clicked += new global::System.EventHandler(this.OnOchoClicked);
		this.nueve.Clicked += new global::System.EventHandler(this.OnNueveClicked);
		this.division.Clicked += new global::System.EventHandler(this.OnDivisionClicked);
		this.cuatro.Clicked += new global::System.EventHandler(this.OnCuatroClicked);
		this.cinco.Clicked += new global::System.EventHandler(this.OnCincoClicked);
		this.seis.Clicked += new global::System.EventHandler(this.OnSeisClicked);
		this.multiplicacion.Clicked += new global::System.EventHandler(this.OnMultiplicacionClicked);
		this.uno.Clicked += new global::System.EventHandler(this.OnUnoClicked);
		this.dos.Clicked += new global::System.EventHandler(this.OnDosClicked);
		this.tres.Clicked += new global::System.EventHandler(this.OnTresClicked);
		this.resta.Clicked += new global::System.EventHandler(this.OnRestaClicked);
		this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		this.cero.Clicked += new global::System.EventHandler(this.OnCeroClicked);
		this.button15.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
		this.suma.Clicked += new global::System.EventHandler(this.OnSumaClicked);
	}
}
